const APP_VERSION = '0.9.0';
const STORAGE_KEY = 'harbor-budget-state-v1';
const supabaseClient = window.supabase?.createClient(window.BUDGETEER_SUPABASE.url, window.BUDGETEER_SUPABASE.publishableKey);
const GROUPS = [
  ['Weekly Basics', ['Groceries','General','Gas','Kids']],
  ['Monthly Autopay', ['Mortgage','Tithing/Fast Offerings','Ballet','Piano Lessons','Water & Sewage','Dominion','Spotify','Gerber Life Insurance','Transamerica','T-Mobile Internet','Google Fi','Tello','Yaris','Discover Card','Bank Fees, Interest & Stuff','Tac Mission']],
  ['Often Expenses', ['Pets','Date $/Restaurants','Family Fun/Travel','Auto Maintenance','Home Maintenance','Birthdays','Anniversary','Christmas/Easter/Holidays']],
  ['Yearly Expenses', ['Jess Life Insurance','YNAB','H&R Block','GEICO Car Insurance','Auto Registration','Amerigas','Jess AFAA CEUs','Personal Property Tax','Garments','Taxes']],
  ['Other Stuff', ['Jessica Business','Jessica Stuff','Ammon Stuff']]
];
const NOTES = {'Google Fi':'$129 without Tac; J&J pay $50','Tello':'$19/month starting in August'};
const uid = (prefix='id') => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const monthKey = d => { const x = d ? new Date(`${d}T12:00:00`) : new Date(); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`; };
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const categorySeed = () => Object.fromEntries(GROUPS.flatMap(([group,names])=>names.map(name=>[name,{id:uid('cat'),name,group,note:NOTES[name]||'',targetMonth:group==='Yearly Expenses'?'12':'',targetAmount:'',savings:0,plans:{}}])));
const initialState = () => ({version:1,categories:categorySeed(),accounts:[],transactions:[],assignments:{},openingFunds:0,openingFundsMonth:''});
const blankState = () => ({version:1,categories:{},accounts:[],transactions:[],assignments:{},openingFunds:0,openingFundsMonth:''});
let state = initialState();
let activeMonth = monthKey();
let deferredInstall;
let authMode = 'signin';
let syncTimer;
let isPullingCloud = false;
let cloudHouseholdId = null;

function loadState(){try{const raw=localStorage.getItem(userStorageKey()); return raw?JSON.parse(raw):initialState();}catch{return initialState();}}
function userStorageKey(){return `${STORAGE_KEY}:${window.currentBudgetUser?.id||'guest'}`;}
function save(){localStorage.setItem(userStorageKey(),JSON.stringify(state));if(window.currentBudgetUser&&!isPullingCloud)queueCloudSave();}
function queueCloudSave(){clearTimeout(syncTimer);syncTimer=setTimeout(pushCloudSnapshot,700);}
async function getHouseholdId(){if(cloudHouseholdId)return cloudHouseholdId;const {data,error}=await supabaseClient.from('household_members').select('household_id').eq('user_id',window.currentBudgetUser.id).limit(1).maybeSingle();if(error)throw error;cloudHouseholdId=data?.household_id||null;return cloudHouseholdId;}
async function pushCloudSnapshot(){if(!window.currentBudgetUser||!supabaseClient||!navigator.onLine)return;try{const householdId=await getHouseholdId();if(!householdId)return;const {error}=await supabaseClient.from('budget_snapshots').upsert({household_id:householdId,data:state,updated_at:new Date().toISOString()});if(error)throw error;}catch(error){console.warn('Budget will sync when online:',error.message);}}
async function pullCloudSnapshot(){if(!window.currentBudgetUser||!supabaseClient)return;try{const householdId=await getHouseholdId();if(!householdId)return;const {data,error}=await supabaseClient.from('budget_snapshots').select('data').eq('household_id',householdId).maybeSingle();if(error)throw error;const local=localStorage.getItem(userStorageKey());if(data?.data){isPullingCloud=true;state=data.data;localStorage.setItem(userStorageKey(),JSON.stringify(state));isPullingCloud=false;}else if(local){await pushCloudSnapshot();}else{save();await pushCloudSnapshot();}render();}catch(error){isPullingCloud=false;console.warn('Using offline budget cache:',error.message);}}
function category(name){return state.categories[name];}
function monthTransactions(m=activeMonth){return state.transactions.filter(t=>t.date?.slice(0,7)===m);}
function assignments(m=activeMonth){return state.assignments[m]||{};}
function incomeTotal(m){return monthTransactions(m).filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount),0);}
function expenseTotal(m){return monthTransactions(m).filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount),0);}
function assignedTotal(m){return Object.values(assignments(m)).reduce((a,v)=>a+Number(v||0),0);}
function spentFor(name,m=activeMonth){return monthTransactions(m).filter(t=>t.type==='expense'&&t.category===name).reduce((a,t)=>a+Number(t.amount),0);}
function savedFor(name){return Number(category(name)?.savings||0);}
function planSuggestion(name,m=activeMonth){const d=new Date(`${m}-01T12:00:00`); d.setMonth(d.getMonth()-1); const prior=monthKey(d); const spent=spentFor(name,prior); const cat=category(name); if(cat?.targetAmount&&cat.targetMonth){const year=d.getFullYear()+(Number(cat.targetMonth)<d.getMonth()+1?1:0); const due=new Date(`${year}-${String(cat.targetMonth).padStart(2,'0')}-01T12:00:00`); const months=Math.max(1,(due.getFullYear()-d.getFullYear())*12+due.getMonth()-d.getMonth()); return Math.max(0,Number(cat.targetAmount)/months); } return spent;}
function availableToAssign(m=activeMonth){const openingFunds=m===state.openingFundsMonth?Number(state.openingFunds||0):0;return incomeTotal(m)+openingFunds-assignedTotal(m);}
function creditCardReady(){return state.transactions.filter(t=>t.type==='expense'&&t.accountId&&state.accounts.find(a=>a.id===t.accountId)?.type==='credit').reduce((a,t)=>a+Number(t.amount),0)-state.transactions.filter(t=>t.type==='transfer'&&t.toAccountId&&state.accounts.find(a=>a.id===t.toAccountId)?.type==='credit').reduce((a,t)=>a+Number(t.amount),0);}
function accountBalance(a){let total=Number(a.openingBalance||0); for(const t of state.transactions){if(t.accountId===a.id){if(t.type==='income') total+=Number(t.amount); if(t.type==='expense') total-=Number(t.amount); if(t.type==='transfer') total-=Number(t.amount);} if(t.toAccountId===a.id&&t.type==='transfer') total+=Number(t.amount);} return total;}
function categoryRemaining(name,m=activeMonth){return Number(assignments(m)[name]||0)-spentFor(name,m);}
function render(){document.getElementById('month-title').textContent=new Date(`${activeMonth}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'}); document.getElementById('available-to-assign').textContent=money(availableToAssign()); document.getElementById('assigned-total').textContent=money(assignedTotal()); document.getElementById('spent-total').textContent=money(expenseTotal(activeMonth)); document.getElementById('cc-ready-total').textContent=money(Math.max(0,creditCardReady())); document.getElementById('header-version').textContent=`v${APP_VERSION}`; document.getElementById('settings-version').textContent=`v${APP_VERSION}`; renderCategories(); renderTransactions(); renderAccounts(); renderSettings();}
function renderCategories(){const root=document.getElementById('category-groups');const grouped={};for(const [group] of GROUPS)grouped[group]=[];for(const c of Object.values(state.categories)){grouped[c.group]??=[];grouped[c.group].push(c.name);}root.innerHTML=Object.entries(grouped).filter(([,names])=>names.length).map(([group,names])=>`<div class="category-group"><h3>${esc(group)}</h3><div class="category-header"><div>Category</div><div>Planned</div><div>Assigned</div><div>Spent</div><div>Remaining</div><div>Savings</div></div>${names.map(name=>{const c=category(name),assigned=Number(assignments()[name]||0),spent=spentFor(name),rem=assigned-spent,savings=savedFor(name);return `<div class="envelope"><div class="category"><button type="button" class="category-link" data-category="${esc(name)}">${esc(name)}</button><div class="category-note">${esc(c.note||'')}</div></div><div class="metric"><label>Planned</label><strong>${money(c.plans?.[activeMonth]??planSuggestion(name))}</strong></div><div class="metric"><label>Assigned</label><strong>${money(assigned)}</strong></div><div class="metric"><label>Spent</label><strong>${money(spent)}</strong></div><div class="metric ${rem<0?'negative':''}"><label>Remaining</label><strong>${money(rem)}</strong></div><div class="metric savings"><label>Savings</label><strong>${money(savings)}</strong></div></div>`}).join('')}</div>`).join('');root.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>openCategoryModal(b.dataset.category));}
function renderTransactions(){document.getElementById('transaction-month').value=activeMonth; const filter=document.getElementById('transaction-account-filter'); const old=filter.value; filter.innerHTML='<option value="all">All accounts</option>'+state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join(''); filter.value=state.accounts.some(a=>a.id===old)?old:'all'; const rows=monthTransactions(activeMonth).filter(t=>filter.value==='all'||t.accountId===filter.value||t.toAccountId===filter.value).sort((a,b)=>b.date.localeCompare(a.date)); document.getElementById('transaction-list').innerHTML=rows.length?rows.map(t=>{const acct=state.accounts.find(a=>a.id===t.accountId)?.name||'—'; const cat=t.category||({income:'Income',transfer:'Transfer'}[t.type]||'—'); return `<tr><td>${esc(t.date)}</td><td>${esc(t.payee||t.type)}</td><td>${esc(acct)}</td><td>${esc(cat)}</td><td class="${t.type==='income'?'amount-in':'amount-out'}">${t.type==='income'?'+':'−'}${money(t.amount)}</td><td>${t.cleared?'Cleared':'Uncleared'}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No transactions for this month.</td></tr>';}
function renderAccounts(){document.getElementById('accounts-list').innerHTML=state.accounts.length?state.accounts.map(a=>`<article class="account-card"><span class="account-type">${esc(a.type)}</span><h3>${esc(a.name)}</h3><div class="account-balance">${money(accountBalance(a))}</div><small>Opening balance ${money(a.openingBalance)}</small></article>`).join(''):'<div class="panel empty">Add your checking, savings, and credit-card accounts to get started.</div>'; document.getElementById('reconcile-panel').innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="setting-row"><div><strong>${esc(a.name)}</strong><small>Current balance ${money(accountBalance(a))}</small></div><button class="secondary" data-reconcile="${a.id}">Reconcile</button></div>`).join(''):'<div class="empty">Add an account to begin reconciliation.</div>'; document.querySelectorAll('[data-reconcile]').forEach(b=>b.onclick=()=>openReconcile(b.dataset.reconcile));}
function renderSettings(){document.getElementById('settings-categories').innerHTML=Object.values(state.categories).map(c=>`<div class="setting-row"><div><strong>${esc(c.name)}</strong><small>${esc(c.group)}${c.note?' · '+esc(c.note):''}</small></div><button class="secondary" data-edit-category="${esc(c.name)}">Edit</button></div>`).join(''); document.querySelectorAll('[data-edit-category]').forEach(b=>b.onclick=()=>openCategoryModal(b.dataset.editCategory));}
function parseCsvLine(line){const cells=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cell+='"';i++;}else if(ch==='"'){quoted=!quoted;}else if(ch===','&&!quoted){cells.push(cell.trim());cell='';}else cell+=ch;}cells.push(cell.trim());return cells;}
function parseCsv(text){return text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim()).map(parseCsvLine);}
function importCsvFile(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const rows=parseCsv(String(reader.result));if(!rows.length)throw new Error('The CSV file is empty.');const headers=rows[0].map(h=>h.toLowerCase().replace(/\s+/g,' ').trim());const categoryIndex=headers.indexOf('category'),amountIndex=headers.indexOf('monthly plan amount'),groupIndex=headers.indexOf('group');if(categoryIndex<0||amountIndex<0||groupIndex<0)throw new Error('The CSV must contain Category, Monthly plan amount, and Group columns.');let imported=0;for(const row of rows.slice(1)){const name=(row[categoryIndex]||'').trim(),group=(row[groupIndex]||'').trim(),amountText=(row[amountIndex]||'').replace(/[$,]/g,'').trim();if(!name)continue;const amount=Number(amountText||0);if(!Number.isFinite(amount)||amount<0)throw new Error(`Invalid amount for ${name}.`);const existing=category(name);if(existing){existing.group=group||existing.group;existing.plans??={};existing.plans[activeMonth]=amount;}else{state.categories[name]={id:uid('cat'),name,group:group||'Other Stuff',note:'',targetMonth:'',targetAmount:'',savings:0,plans:{[activeMonth]:amount}};}imported++;}save();render();alert(`Imported ${imported} monthly plan${imported===1?'':'s'} for ${new Date(`${activeMonth}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'})}.`);}catch(error){alert(error.message||'Could not read that CSV file.');}event.target.value='';};reader.readAsText(file);}
async function wipeBudget(){if(!confirm('Wipe this budget and start fresh? This removes all categories, accounts, transactions, plans, savings, and the cloud snapshot.'))return;if(!confirm('This cannot be undone unless you have a backup. Continue?'))return;clearTimeout(syncTimer);try{if(window.currentBudgetUser&&supabaseClient){const householdId=await getHouseholdId();if(householdId){const {error}=await supabaseClient.from('budget_snapshots').delete().eq('household_id',householdId);if(error)throw error;}}localStorage.removeItem(userStorageKey());state=blankState();localStorage.setItem(userStorageKey(),JSON.stringify(state));render();alert('Budget wiped. The app is now completely empty.');}catch(error){alert(`The budget was not fully wiped: ${error.message}`);}}
function modal(title,body){const root=document.getElementById('modal-root'); root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${title}</h2>${body}</div></div>`; root.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML='';}; return root.querySelector('.modal');}
function closeModal(){document.getElementById('modal-root').innerHTML='';}
function openAssignment(){const names=Object.keys(state.categories); const m=modal('Assign money',`<div class="notice">Available to assign: <strong>${money(availableToAssign())}</strong></div><div class="form-grid"><label class="form-field full">Category<select id="assign-category">${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label><label class="form-field">Amount<input id="assign-amount" type="number" min="0" step="0.01" value="${planSuggestion(names[0])||''}"></label></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save-assignment">Assign</button></div>`); m.querySelector('[data-close]').onclick=closeModal; m.querySelector('#save-assignment').onclick=()=>{const n=m.querySelector('#assign-category').value, amount=Number(m.querySelector('#assign-amount').value); if(!amount||amount<0)return; state.assignments[activeMonth]??={}; state.assignments[activeMonth][n]=(state.assignments[activeMonth][n]||0)+amount; category(n).plans[activeMonth]=Number(m.querySelector('#assign-amount').value); save();closeModal();render();};}
function openTransaction(){const options=Object.keys(state.categories); const accounts=state.accounts; const m=modal('Add transaction',`<div class="form-grid"><label class="form-field">Type<select id="tx-type"><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select></label><label class="form-field">Date<input id="tx-date" type="date" value="${activeMonth}-${String(new Date().getDate()).padStart(2,'0')}"></label><label class="form-field full">Payee / description<input id="tx-payee" placeholder="e.g. Grocery store"></label><label class="form-field">Amount<input id="tx-amount" type="number" min="0" step="0.01"></label><label class="form-field" id="account-field">Account<select id="tx-account">${accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label class="form-field" id="category-field">Category<select id="tx-category">${options.map(n=>`<option>${esc(n)}</option>`).join('')}</select></label><label class="form-field full">Memo<input id="tx-memo"></label><label class="form-field"><input id="tx-cleared" type="checkbox" checked> Cleared</label></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save-tx">Save transaction</button></div>`); const type=m.querySelector('#tx-type'); const catField=m.querySelector('#category-field'); const accountField=m.querySelector('#account-field'); type.onchange=()=>{catField.style.display=type.value==='expense'?'block':'none';}; m.querySelector('[data-close]').onclick=closeModal; m.querySelector('#save-tx').onclick=()=>{const amount=Number(m.querySelector('#tx-amount').value); if(!amount||!accounts.length)return; const t={id:uid('tx'),type:type.value,date:m.querySelector('#tx-date').value,amount,payee:m.querySelector('#tx-payee').value,memo:m.querySelector('#tx-memo').value,accountId:m.querySelector('#tx-account').value,category:type.value==='expense'?m.querySelector('#tx-category').value:'',cleared:m.querySelector('#tx-cleared').checked}; if(type.value==='expense'&&categoryRemaining(t.category)-amount<0&&savedFor(t.category)<amount-categoryRemaining(t.category)){alert('This category needs a transfer from another category before it can cover this expense.');return;} state.transactions.push(t); if(type.value==='expense'){const c=category(t.category); const monthSpent=spentFor(t.category,t.date.slice(0,7)); if(monthSpent>Number(state.assignments[t.date.slice(0,7)]?.[t.category]||0)){c.savings=Math.max(0,c.savings-(monthSpent-Number(state.assignments[t.date.slice(0,7)]?.[t.category]||0)));}} save();closeModal();render();};}
function openAccount(){const m=modal('Add account',`<div class="form-grid"><label class="form-field full">Account name<input id="account-name" placeholder="e.g. Main checking"></label><label class="form-field">Type<select id="account-type"><option value="checking">Checking</option><option value="savings">Savings</option><option value="credit">Credit card</option></select></label><label class="form-field">Opening balance<input id="account-opening" type="number" step="0.01" value="0"></label></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save-account">Add account</button></div>`); m.querySelector('[data-close]').onclick=closeModal; m.querySelector('#save-account').onclick=()=>{const name=m.querySelector('#account-name').value.trim();if(!name)return;const type=m.querySelector('#account-type').value;const openingBalance=Number(m.querySelector('#account-opening').value||0);state.accounts.push({id:uid('acct'),name,type,openingBalance});if(type!=='credit'&&openingBalance>0){state.openingFunds=Number(state.openingFunds||0)+openingBalance;if(!state.openingFundsMonth)state.openingFundsMonth=activeMonth;}save();closeModal();render();};}
function openCategoryModal(name){const c=category(name); const m=modal(name?`Edit ${esc(name)}`:'Add category',`<div class="form-grid"><label class="form-field full">Name<input id="cat-name" value="${esc(c?.name||'')}"></label><label class="form-field">Group<select id="cat-group">${GROUPS.map(([g])=>`<option ${c?.group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label class="form-field">Due month (yearly)<input id="cat-month" type="number" min="1" max="12" value="${c?.targetMonth||''}"></label><label class="form-field">Annual target amount<input id="cat-target" type="number" min="0" step="0.01" value="${c?.targetAmount||''}"></label><label class="form-field full">Note<input id="cat-note" value="${esc(c?.note||'')}"></label></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button>${c?'<button class="secondary danger" id="delete-category">Delete</button>':''}<button class="primary" id="save-category">Save</button></div>`);m.querySelector('[data-close]').onclick=closeModal;m.querySelector('#save-category').onclick=()=>{const newName=m.querySelector('#cat-name').value.trim();if(!newName)return; if(c&&newName!==name){state.categories[newName]={...c,name:newName};delete state.categories[name];for(const month of Object.keys(state.assignments))if(state.assignments[month][name]){state.assignments[month][newName]=state.assignments[month][name];delete state.assignments[month][name];}}else if(!c)state.categories[newName]={id:uid('cat'),name:newName,group:m.querySelector('#cat-group').value,note:'',savings:0,plans:{}};const x=state.categories[newName];x.group=m.querySelector('#cat-group').value;x.note=m.querySelector('#cat-note').value;x.targetMonth=m.querySelector('#cat-month').value;x.targetAmount=m.querySelector('#cat-target').value;save();closeModal();render();}; if(c)m.querySelector('#delete-category').onclick=()=>{if(confirm(`Delete ${name}? Existing transactions will remain.`)){delete state.categories[name];save();closeModal();render();}};}
function openReconcile(id){const a=state.accounts.find(x=>x.id===id);const m=modal(`Reconcile ${esc(a.name)}`,`<p>Current app balance: <strong>${money(accountBalance(a))}</strong></p><div class="form-grid"><label class="form-field">Statement date<input id="stmt-date" type="date"></label><label class="form-field">Statement balance<input id="stmt-balance" type="number" step="0.01"></label></div><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save-reconcile">Save reconciliation</button></div>`);m.querySelector('[data-close]').onclick=closeModal;m.querySelector('#save-reconcile').onclick=()=>{a.reconciliation={date:m.querySelector('#stmt-date').value,balance:Number(m.querySelector('#stmt-balance').value)};save();closeModal();render();};}
function setup(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');render();});document.getElementById('prev-month').onclick=()=>shiftMonth(-1);document.getElementById('next-month').onclick=()=>shiftMonth(1);document.getElementById('today-month').onclick=()=>{activeMonth=monthKey();render();};document.getElementById('add-assignment').onclick=openAssignment;document.getElementById('add-transaction').onclick=openTransaction;document.getElementById('add-account').onclick=openAccount;document.getElementById('add-category').onclick=()=>openCategoryModal();document.getElementById('transaction-month').onchange=e=>{activeMonth=e.target.value;render();};document.getElementById('transaction-account-filter').onchange=renderTransactions;document.getElementById('backup-btn').onclick=backup;document.getElementById('restore-btn').onclick=()=>document.getElementById('restore-input').click();document.getElementById('restore-input').onchange=restore;document.getElementById('reset-demo').onclick=wipeBudget;document.getElementById('wipe-budget').onclick=wipeBudget;document.getElementById('import-csv').onclick=()=>document.getElementById('csv-input').click();document.getElementById('csv-input').onchange=importCsvFile;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.getElementById('install-btn').hidden=false;});document.getElementById('install-btn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;}};render();}
function shiftMonth(delta){const d=new Date(`${activeMonth}-01T12:00:00`);d.setMonth(d.getMonth()+delta);activeMonth=monthKey(d);render();}
function backup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`harbor-budget-${monthKey()}.json`;a.click();URL.revokeObjectURL(a.href);}
function restore(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported.categories||!imported.transactions)throw new Error();state=imported;save();render();alert('Budget restored.');}catch{alert('That file is not a valid Harbor Budget backup.');}};reader.readAsText(file);e.target.value='';}
async function showApp(session){document.getElementById('auth-gate').hidden=true;document.getElementById('app-shell').hidden=false;window.currentBudgetUser=session?.user||null;state=loadState();if(!state.openingFundsMonth&&state.accounts.length){state.openingFunds=state.accounts.filter(a=>a.type!=='credit'&&Number(a.openingBalance)>0).reduce((sum,a)=>sum+Number(a.openingBalance),0);state.openingFundsMonth=activeMonth;save();}render();await pullCloudSnapshot();}
function showAuth(){document.getElementById('auth-gate').hidden=false;document.getElementById('app-shell').hidden=true;}
function setupAuth(){const form=document.getElementById('auth-form');const toggle=document.getElementById('auth-toggle');const title=document.getElementById('auth-title');const subtitle=document.getElementById('auth-subtitle');const submit=document.getElementById('auth-submit');const message=document.getElementById('auth-message');toggle.onclick=()=>{authMode=authMode==='signin'?'signup':'signin';title.textContent=authMode==='signin'?'Sign in to your budget':'Create your budget account';subtitle.textContent=authMode==='signin'?'Your account keeps your budget ready on every device.':'Start your private envelope budget with a free account.';submit.textContent=authMode==='signin'?'Sign in':'Create account';toggle.textContent=authMode==='signin'?'Create a new account':'I already have an account';message.textContent='';};form.onsubmit=async e=>{e.preventDefault();message.className='auth-message';message.textContent='Working…';const email=document.getElementById('auth-email').value.trim();const password=document.getElementById('auth-password').value;const result=authMode==='signin'?await supabaseClient.auth.signInWithPassword({email,password}):await supabaseClient.auth.signUp({email,password});if(result.error){message.textContent=result.error.message;return;}if(authMode==='signup'&&!result.data.session){message.className='auth-message success';message.textContent='Account created. Check your email to confirm it, then sign in.';}else{message.textContent='';}};}
async function initAuth(){setupAuth();document.getElementById('sign-out').onclick=()=>supabaseClient?.auth.signOut();if(!supabaseClient){showAuth();document.getElementById('auth-message').textContent='Supabase configuration is missing.';return;}supabaseClient.auth.onAuthStateChange((_event,session)=>{if(session)showApp(session);else showAuth();});const {data}=await supabaseClient.auth.getSession();if(data.session)showApp(data.session);else showAuth();}
window.addEventListener('online',()=>{if(window.currentBudgetUser)pushCloudSnapshot();});
setup();
initAuth();
